# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a7af64e2e9217ac45ff5b289c7b479d5684c2d744434bc24ce096918a4a5a68eb13abb9aa610b3deeb400bd1a7b1c1d7d17c4e1568ca3666a6eff34da54972b

test:
  secret_key_base: 4baaff9356ae4c23ccff268a37e43de6b89af698f42512ec03913262081150276d08c5e296f95068cedc4958abb2722652b671f681d6227fffda4289ae123e8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
